<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.tianji</groupId>
        <artifactId>tianjitown-parent</artifactId>
        <version>1.3.0</version>
    </parent>
    <artifactId>tianjitown-integrations</artifactId>
    <name>TianjiTown Integrations</name>
    <dependencies>
        <dependency>
            <groupId>cn.tianji</groupId>
            <artifactId>tianjitown-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.papermc.paper</groupId>
            <artifactId>paper-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.github.Zrips</groupId>
            <artifactId>Residence</artifactId>
            <scope>provided</scope>
            <exclusions>
                <exclusion><groupId>*</groupId><artifactId>*</artifactId></exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.github.MilkBowl</groupId>
            <artifactId>VaultAPI</artifactId>
            <scope>provided</scope>
            <exclusions>
                <exclusion><groupId>*</groupId><artifactId>*</artifactId></exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.sk89q.worldguard</groupId>
            <artifactId>worldguard-bukkit</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>

