name: TianjiTown
version: '${project.version}'
main: org.allivlisey.tianjitown.paper.TianjiTownPlugin
api-version: '26.2'
load: POSTWORLD
authors: [Allivilsey]
libraries:
  - 'com.zaxxer:HikariCP:${hikari.version}'
  - 'org.flywaydb:flyway-core:${flyway.version}'
  - 'org.xerial:sqlite-jdbc:${sqlite.version}'
softdepend: [Vault, Residence, QuickShop-Hikari, Jobs, GlobalMarketPlus, XConomy, WorldBorder, HuskSync]
commands:
  tianjitown-callback:
    description: 小镇聊天按钮回调
  tianjitown:
    description: TianjiTown 管理命令
    usage: /tianjitown help
permissions:
  tianjitown.admin:
    description: TianjiTown 全部管理权限
    default: op
